# Generated by Django 5.2.7 on 2025-11-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_upvotes_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
