# Generated by Django 5.2.7 on 2025-11-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_latitude_issue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Road', 'Road Damage'), ('Waste', 'Waste Management'), ('Water', 'Water Supply'), ('Electricity', 'Electricity'), ('other', 'Other')], max_length=50),
        ),
    ]
